191225

diff --git a/scripts/mm5d-editmainconf b/scripts/mm5d-editmainconf
--- a/scripts/mm5d-editmainconf
+++ b/scripts/mm5d-editmainconf
@@ -1,11 +1,11 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
-# | MM3D v0.4 * Growing house controlling and remote monitoring system         |
-# | Copyright (C) 2018-2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>      |
-# | mm3d-editmainconf                                                          |
+# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
+# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
+# | mm5d-editmainconf                                                          |
 # | Edit main configuration file                                               |
 # +----------------------------------------------------------------------------+
-#
+
 #   This program is free software: you can redistribute it and/or modify it
 # under the terms of the European Union Public License 1.1 version.
 #
@@ -13,15 +13,24 @@
 # ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 # FOR A PARTICULAR PURPOSE.
 
-CFGFILE="/usr/local/etc/mm3d/mm3d.ini"
+# Exit codes:
+#   0: normal exit
+#   1: configuration file is missing
+
+#CFGFILE="/etc/mm5d/mm5d.ini"
+CFGFILE="/usr/local/etc/mm5d/mm5d.ini"
 if [ ! -f $CFGFILE ]
 then
   echo "ERROR: Cannot open configuration file!"
 exit 1
 fi
 
-mm3d-stopdaemon
-sudo editor $CFGFILE
-mm3d-updatestartpage
-mm3d-startdaemon
-exit 0
+sudo mm5d-editmainconf.bin $CFGFILE
+if [ $? -eq 0 ]
+then
+  mm5d-stopdaemon
+  mm5d-updatestartpage
+  mm5d-startdaemon
+fi
+
+
