191225

diff --git a/scripts/mm5d-editenvirconf b/scripts/mm5d-editenvirconf
--- a/scripts/mm5d-editenvirconf
+++ b/scripts/mm5d-editenvirconf
@@ -1,11 +1,11 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
 # | MM5D v0.1 * Growing house controlling and remote monitoring system         |
-# | Copyright (C) 2019 Pozsar Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
-# | cfg_example.sh                                                             |
-# | User's program configurator                                                |
+# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
+# | mm5d-editenvirconf                                                         |
+# | Edit environment configuration file                                        |
 # +----------------------------------------------------------------------------+
-#
+
 #   This program is free software: you can redistribute it and/or modify it
 # under the terms of the European Union Public License 1.1 version.
 #
@@ -13,3 +13,20 @@
 # ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 # FOR A PARTICULAR PURPOSE.
 
+# Exit codes:
+#   0: normal exit
+#   1: configuration file is missing
+
+CFGFILE="/usr/local/etc/mm5d/envir.ini"
+if [ ! -f $CFGFILE ]
+then
+  echo "ERROR: Cannot open configuration file!"
+exit 1
+fi
+
+sudo mm5d-editenvirconf.bin $CFGFILE
+if [ $? -eq 0 ]
+then
+  mm3d-stopdaemon
+  mm3d-startdaemon
+fi
