230323

diff --git a/scripts/mm5d-editenvirconf b/scripts/mm5d-editenvirconf
--- a/scripts/mm5d-editenvirconf
+++ b/scripts/mm5d-editenvirconf
@@ -1,7 +1,7 @@
 #!/bin/bash
 # +----------------------------------------------------------------------------+
-# | MM5D v0.5 * Growing house controlling and remote monitoring system         |
-# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
+# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
+# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
 # | mm5d-editenvirconf                                                         |
 # | Edit environment configuration file                                        |
 # +----------------------------------------------------------------------------+
@@ -15,14 +15,14 @@
 
 # Exit codes:
 #   0: normal exit
-#   1: configuration file is missing
+#  14: cannot open environment characteristic configuration file
 
 #CFGFILE="/etc/mm5d/envir.ini"
 CFGFILE="/usr/local/etc/mm5d/envir.ini"
 if [ ! -f $CFGFILE ]
 then
-  echo "ERROR: Cannot open configuration file!"
-exit 1
+  echo "ERROR: Cannot open environment characteristic configuration file!"
+exit 14
 fi
 
 sudo mm5d-editenvirconf.bin $CFGFILE
